/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplojmenu;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Global Tech
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel1.setText("Ejemplo de Menu");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save_48px.png"))); // NOI18N
        jButton1.setText("Guardar Archivo");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print_48px.png"))); // NOI18N
        jButton2.setText("Imprimir Archivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivos");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Help_48px.png"))); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu4.setForeground(new java.awt.Color(204, 0, 0));
        jMenu4.setText("Modificar");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(204, 0, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Edit Property_48px.png"))); // NOI18N
        jMenuItem2.setText("Editar");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(204, 0, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Trash Can_48px.png"))); // NOI18N
        jMenuItem3.setText("Borrar");
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(51, 153, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save_48px.png"))); // NOI18N
        jMenu5.setText("Guardar");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 153, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Microsoft Excel_48px.png"))); // NOI18N
        jMenuItem5.setText("Excel");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(0, 153, 0));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Microsoft Word_48px.png"))); // NOI18N
        jMenuItem6.setText("Word");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(0, 153, 0));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PDF_48px.png"))); // NOI18N
        jMenuItem7.setText("PDF");
        jMenu5.add(jMenuItem7);

        jMenu1.add(jMenu5);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(153, 153, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print_48px.png"))); // NOI18N
        jMenuItem4.setText("Imprimir");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Internet");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenu6.setForeground(new java.awt.Color(204, 0, 204));
        jMenu6.setText("Multimedia");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vintage Camera_48px.png"))); // NOI18N
        jMenuItem8.setText("Fotos");
        jMenu6.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circled Play_48px.png"))); // NOI18N
        jMenuItem9.setText("Musica");
        jMenu6.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Play Button_48px.png"))); // NOI18N
        jMenuItem10.setText("Videos");
        jMenu6.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Movie Projector_48px.png"))); // NOI18N
        jMenuItem11.setText("Peliculas");
        jMenu6.add(jMenuItem11);

        jMenu2.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/About_48px.png"))); // NOI18N
        jMenu7.setText("Busqueda");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Microsoft Edge_48px.png"))); // NOI18N
        jMenuItem12.setText("Internet Explorer");
        jMenu7.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chrome_48px.png"))); // NOI18N
        jMenuItem13.setText("Google Chrome");
        jMenu7.add(jMenuItem13);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Redes");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Settings_48px.png"))); // NOI18N
        jMenuItem14.setText("Configurar Conexión");
        jMenu3.add(jMenuItem14);

        jMenu8.setForeground(new java.awt.Color(0, 51, 204));
        jMenu8.setText("Cuentas");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Facebook_48px.png"))); // NOI18N
        jMenuItem15.setText("Facebook");
        jMenu8.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Twitter_48px.png"))); // NOI18N
        jMenuItem16.setText("Twitter");
        jMenu8.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Instagram_48px.png"))); // NOI18N
        jMenuItem17.setText("Instagram");
        jMenu8.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem18.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Android OS_48px.png"))); // NOI18N
        jMenuItem18.setText("Android OS");
        jMenu8.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem19.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Email_48px.png"))); // NOI18N
        jMenuItem19.setText("Email");
        jMenu8.add(jMenuItem19);

        jMenu3.add(jMenu8);

        jMenuBar1.add(jMenu3);

        jMenu9.setText("Herramienta");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu10.setText("Color Panel");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jCheckBoxMenuItem1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Activar Color");
        jCheckBoxMenuItem1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem1ItemStateChanged(evt);
            }
        });
        jMenu10.add(jCheckBoxMenuItem1);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem20.setText("Blanco");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem20);

        jMenu9.add(jMenu10);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Evento Abrir:
        JOptionPane.showInputDialog("Ingrese el Nombre del Archivo");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // Guardar en formato Excel
        JOptionPane.showMessageDialog(this, "Archivo guardado como Excel .XML ");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // Panel Color Blanco
        jPanel1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jCheckBoxMenuItem1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ItemStateChanged
        // Activar Color
        if(jCheckBoxMenuItem1.isSelected()){
            //Si esta activo
            jPanel1.setBackground(new Color(255,255,204));
        }else {
            // No esta activo
            jPanel1.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
                    
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
