/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Itzayana
 */
public class State2 extends javax.swing.JFrame {
    String [] n= new String[100];
    String []m= new String[100];
    
    
    /**
     * Creates new form State
     */
    public State2() {
        initComponents();
        N.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estados = new javax.swing.ButtonGroup();
        R = new javax.swing.JLabel();
        Vp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        Acepto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        FS = new javax.swing.JRadioButton();
        NoI = new javax.swing.JRadioButton();
        N = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        R.setBackground(new java.awt.Color(0, 0, 255));
        R.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        R.setText("        Vista Previa");
        R.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        getContentPane().add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 120));

        Vp.setBackground(new java.awt.Color(255, 51, 255));
        Vp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Vp.setText("Vista Previa");
        Vp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 3, true));
        Vp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VpActionPerformed(evt);
            }
        });
        getContentPane().add(Vp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, 60));

        jLabel2.setBackground(new java.awt.Color(0, 153, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Numero de Equipo ;");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 30));

        r.setEditable(false);
        r.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        r.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 160, 40, 30));

        Acepto.setBackground(new java.awt.Color(153, 51, 255));
        Acepto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Acepto.setText("Aceptar");
        Acepto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 4, true));
        Acepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptoActionPerformed(evt);
            }
        });
        getContentPane().add(Acepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, 50));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true), "Opciones de Estado del Computador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        FS.setBackground(new java.awt.Color(51, 102, 255));
        Estados.add(FS);
        FS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FS.setText("Fuera de Servicio.");
        FS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NoI.setBackground(new java.awt.Color(153, 153, 153));
        Estados.add(NoI);
        NoI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NoI.setText("No conecta al Internet.");

        N.setBackground(new java.awt.Color(0, 204, 0));
        Estados.add(N);
        N.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        N.setSelected(true);
        N.setText("Normal.");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoI, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N)
                    .addComponent(FS))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FS, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(N)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 130));

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true), "Estado del Computador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void VpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VpActionPerformed
    m[0]= n[0];
    m[1]= n[1];
    m[2]= n[2];
    m[3]= n[3];
    m[4]= n[4];
    m[5]= n[5];
    m[6]= n[6];
    m[7]= n[7];
    m[8]= n[8];
    m[9]= n[9];
    m[10]= n[10];
    m[11]= n[11];
    m[12]= n[12];
    m[13]= n[13];
    m[14]= n[14];
    m[15]= n[15];
    m[16]= n[16];
    m[17]= n[17];
    m[18]= n[18];
    m[19]= n[19];
    m[20]= n[20];
    m[21]= n[21];
    m[22]= n[22];
    m[23]= n[23];
        if(FS.isSelected()){
       ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
       R.setIcon(imagen);
       this.repaint();
       this.repaint();
    }
    if(NoI.isSelected()){
       ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
       R.setIcon(imagen);
       this.repaint();
       this.repaint();
    }    
    if(N.isSelected()){
        ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/images.png"));
        
        R.setIcon(imagen);
        this.repaint();
        this.repaint();
    }    
    }//GEN-LAST:event_VpActionPerformed

    private void AceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptoActionPerformed
    m[0]= n[0];
    m[1]= n[1];
    m[2]= n[2];
    m[3]= n[3];
    m[4]= n[4];
    m[5]= n[5];
    m[6]= n[6];
    m[7]= n[7];
    m[8]= n[8];
    m[9]= n[9];
    m[10]= n[10];
    m[11]= n[11];
    m[12]= n[12];
    m[13]= n[13];
    m[14]= n[14];
    m[15]= n[15];
    m[16]= n[16];
    m[17]= n[17];
    m[18]= n[18];
    m[19]= n[19];
    m[20]= n[20];
    m[21]= n[21];
    m[22]= n[22];
    m[23]= n[23];
    if(FS.isSelected()){
    if(r.getText().equals(m[0])){ 
    Lab2.Nombre.setEditable(false);
    Lab2.Nombre.setEnabled(false);
    Lab2.Nombre.setBackground(Color.red);
    Lab2.comenzar.setEnabled(false);
    Lab2.Pause.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea2.setIcon(imagen);
    Lab2.Icono.setText("No funciona.");
    Lab2.estado.setText("Fuera de Servicio.");
    Lab2.estado.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[1])){ 
    Lab2.Nombre1.setEditable(false);
    Lab2.Nombre1.setEnabled(false);
    Lab2.Nombre1.setBackground(Color.red);
    Lab2.comenzar1.setEnabled(false);
    Lab2.Pause1.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea39.setIcon(imagen);
    Lab2.Icono1.setText("No funciona.");
    Lab2.estado1.setText("Fuera de Servicio.");
    Lab2.estado1.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[2])){ 
    Lab2.Nombre2.setEditable(false);
    Lab2.Nombre2.setEnabled(false);
    Lab2.Nombre2.setBackground(Color.red);
    Lab2.comenzar2.setEnabled(false);
    Lab2.Pause2.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea41.setIcon(imagen);
    Lab2.Icono2.setText("No funciona.");
    Lab2.estado2.setText("Fuera de Servicio.");
    Lab2.estado2.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[3])){ 
    Lab2.Nombre3.setEditable(false);
    Lab2.Nombre3.setEnabled(false);
    Lab2.Nombre3.setBackground(Color.red);
    Lab2.comenzar3.setEnabled(false);
    Lab2.Pause3.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea43.setIcon(imagen);
    Lab2.Icono3.setText("No funciona.");
    Lab2.estado3.setText("Fuera de Servicio.");
    Lab2.estado3.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[4])){ 
    Lab2.Nombre4.setEditable(false);
    Lab2.Nombre4.setEnabled(false);
    Lab2.Nombre4.setBackground(Color.red);
    Lab2.comenzar4.setEnabled(false);
    Lab2.Pause4.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea45.setIcon(imagen);
    Lab2.Icono4.setText("No funciona.");
    Lab2.estado4.setText("Fuera de Servicio.");
    Lab2.estado4.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[5])){ 
    Lab2.Nombre5.setEditable(false);
    Lab2.Nombre5.setEnabled(false);
    Lab2.Nombre5.setBackground(Color.red);
    Lab2.comenzar5.setEnabled(false);
    Lab2.Pause5.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea47.setIcon(imagen);
    Lab2.Icono5.setText("No funciona.");
    Lab2.estado5.setText("Fuera de Servicio.");
    Lab2.estado5.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[6])){ 
    Lab2.Nombre6.setEditable(false);
    Lab2.Nombre6.setEnabled(false);
    Lab2.Nombre6.setBackground(Color.red);
    Lab2.comenzar6.setEnabled(false);
    Lab2.Pause6.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea3.setIcon(imagen);
    Lab2.Icono6.setText("No funciona.");
    Lab2.estado6.setText("Fuera de Servicio.");
    Lab2.estado6.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[7])){ 
    Lab2.Nombre7.setEditable(false);
    Lab2.Nombre7.setEnabled(false);
    Lab2.Nombre7.setBackground(Color.red);
    Lab2.comenzar7.setEnabled(false);
    Lab2.Pause7.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea5.setIcon(imagen);
    Lab2.Icono7.setText("No funciona.");
    Lab2.estado7.setText("Fuera de Servicio.");
    Lab2.estado7.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[8])){ 
    Lab2.Nombre8.setEditable(false);
    Lab2.Nombre8.setEnabled(false);
    Lab2.Nombre8.setBackground(Color.red);
    Lab2.comenzar8.setEnabled(false);
    Lab2.Pause8.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea7.setIcon(imagen);
    Lab2.Icono8.setText("No funciona.");
    Lab2.estado8.setText("Fuera de Servicio.");
    Lab2.estado8.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[9])){ 
    Lab2.Nombre9.setEditable(false);
    Lab2.Nombre9.setEnabled(false);
    Lab2.Nombre9.setBackground(Color.red);
    Lab2.comenzar9.setEnabled(false);
    Lab2.Pause9.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea9.setIcon(imagen);
    Lab2.Icono9.setText("No funciona.");
    Lab2.estado9.setText("Fuera de Servicio.");
    Lab2.estado9.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[10])){ 
    Lab2.Nombre10.setEditable(false);
    Lab2.Nombre10.setEnabled(false);
    Lab2.Nombre10.setBackground(Color.red);
    Lab2.comenzar10.setEnabled(false);
    Lab2.Pause10.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea11.setIcon(imagen);
    Lab2.Icono10.setText("No funciona.");
    Lab2.estado10.setText("Fuera de Servicio.");
    Lab2.estado10.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[11])){ 
    Lab2.Nombre11.setEditable(false);
    Lab2.Nombre11.setEnabled(false);
    Lab2.Nombre11.setBackground(Color.red);
    Lab2.comenzar11.setEnabled(false);
    Lab2.Pause11.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea13.setIcon(imagen);
    Lab2.Icono11.setText("No funciona.");
    Lab2.estado11.setText("Fuera de Servicio.");
    Lab2.estado11.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[12])){ 
    Lab2.Nombre12.setEditable(false);
    Lab2.Nombre12.setEnabled(false);
    Lab2.Nombre12.setBackground(Color.red);
    Lab2.comenzar12.setEnabled(false);
    Lab2.Pause12.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea15.setIcon(imagen);
    Lab2.Icono12.setText("No funciona.");
    Lab2.estado12.setText("Fuera de Servicio.");
    Lab2.estado12.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[13])){ 
    Lab2.Nombre13.setEditable(false);
    Lab2.Nombre13.setEnabled(false);
    Lab2.Nombre13.setBackground(Color.red);
    Lab2.comenzar13.setEnabled(false);
    Lab2.Pause13.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea17.setIcon(imagen);
    Lab2.Icono13.setText("No funciona.");
    Lab2.estado13.setText("Fuera de Servicio.");
    Lab2.estado13.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[14])){ 
    Lab2.Nombre14.setEditable(false);
    Lab2.Nombre14.setEnabled(false);
    Lab2.Nombre14.setBackground(Color.red);
    Lab2.comenzar14.setEnabled(false);
    Lab2.Pause14.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea19.setIcon(imagen);
    Lab2.Icono14.setText("No funciona.");
    Lab2.estado14.setText("Fuera de Servicio.");
    Lab2.estado14.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[15])){ 
    Lab2.Nombre15.setEditable(false);
    Lab2.Nombre15.setEnabled(false);
    Lab2.Nombre15.setBackground(Color.red);
    Lab2.comenzar15.setEnabled(false);
    Lab2.Pause15.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea21.setIcon(imagen);
    Lab2.Icono15.setText("No funciona.");
    Lab2.estado15.setText("Fuera de Servicio.");
    Lab2.estado15.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[16])){ 
    Lab2.Nombre16.setEditable(false);
    Lab2.Nombre16.setEnabled(false);
    Lab2.Nombre16.setBackground(Color.red);
    Lab2.comenzar16.setEnabled(false);
    Lab2.Pause16.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea23.setIcon(imagen);
    Lab2.Icono16.setText("No funciona.");
    Lab2.estado16.setText("Fuera de Servicio.");
    Lab2.estado16.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[17])){ 
    Lab2.Nombre17.setEditable(false);
    Lab2.Nombre17.setEnabled(false);
    Lab2.Nombre17.setBackground(Color.red);
    Lab2.comenzar17.setEnabled(false);
    Lab2.Pause17.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea25.setIcon(imagen);
    Lab2.Icono17.setText("No funciona.");
    Lab2.estado17.setText("Fuera de Servicio.");
    Lab2.estado17.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[18])){ 
    Lab2.Nombre18.setEditable(false);
    Lab2.Nombre18.setEnabled(false);
    Lab2.Nombre18.setBackground(Color.red);
    Lab2.comenzar18.setEnabled(false);
    Lab2.Pause18.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea27.setIcon(imagen);
    Lab2.Icono18.setText("No funciona.");
    Lab2.estado18.setText("Fuera de Servicio.");
    Lab2.estado18.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[19])){ 
    Lab2.Nombre19.setEditable(false);
    Lab2.Nombre19.setEnabled(false);
    Lab2.Nombre19.setBackground(Color.red);
    Lab2.comenzar19.setEnabled(false);
    Lab2.Pause19.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea29.setIcon(imagen);
    Lab2.Icono19.setText("No funciona.");
    Lab2.estado19.setText("Fuera de Servicio.");
    Lab2.estado19.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[20])){ 
    Lab2.Nombre20.setEditable(false);
    Lab2.Nombre20.setEnabled(false);
    Lab2.Nombre20.setBackground(Color.red);
    Lab2.comenzar20.setEnabled(false);
    Lab2.Pause20.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea31.setIcon(imagen);
    Lab2.Icono20.setText("No funciona.");
    Lab2.estado20.setText("Fuera de Servicio.");
    Lab2.estado20.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[21])){ 
    Lab2.Nombre21.setEditable(false);
    Lab2.Nombre21.setEnabled(false);
    Lab2.Nombre21.setBackground(Color.red);
    Lab2.comenzar21.setEnabled(false);
    Lab2.Pause21.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea33.setIcon(imagen);
    Lab2.Icono21.setText("No funciona.");
    Lab2.estado21.setText("Fuera de Servicio.");
    Lab2.estado21.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[22])){ 
    Lab2.Nombre22.setEditable(false);
    Lab2.Nombre22.setEnabled(false);
    Lab2.Nombre22.setBackground(Color.red);
    Lab2.comenzar22.setEnabled(false);
    Lab2.Pause22.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea35.setIcon(imagen);
    Lab2.Icono22.setText("No funciona.");
    Lab2.estado22.setText("Fuera de Servicio.");
    Lab2.estado22.setBackground(Color.red);
    dispose();
    }
    if(r.getText().equals(m[23])){ 
    Lab2.Nombre23.setEditable(false);
    Lab2.Nombre23.setEnabled(false);
    Lab2.Nombre23.setBackground(Color.red);
    Lab2.comenzar23.setEnabled(false);
    Lab2.Pause23.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/eae998_e2a5b283977b409ba0bc0c76ad6f171a_mv2.jpg"));
    Lab2.Idea37.setIcon(imagen);
    Lab2.Icono23.setText("No funciona.");
    Lab2.estado23.setText("Fuera de Servicio.");
    Lab2.estado23.setBackground(Color.red);
    dispose();
    }
    }
    if(NoI.isSelected()){
    if(r.getText().equals(m[0])){   
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea2.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[1])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea39.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[2])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea41.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[3])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea43.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[4])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea45.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[5])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea47.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[6])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea3.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[7])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea5.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[8])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea7.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[9])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea9.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[10])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea11.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[11])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea13.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[12])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea15.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[13])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea17.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[14])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea19.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[15])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea21.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[16])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea23.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[17])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea25.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[18])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea27.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[19])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea29.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[20])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea31.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[21])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea33.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[22])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea35.setIcon(imagen);
    dispose();
    }
    if(r.getText().equals(m[23])){  
    ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/no-wifi-sign-wi-fi-symbol-wireless-network-vector-1907444.jpg"));
    Lab2.Idea37.setIcon(imagen);
    dispose();
    }
    }
    if(N.isSelected()){
    if(r.getText().equals(m[0])){ 
    Lab2.Nombre.setEditable(true);
    Lab2.Nombre.setEnabled(true);
    Lab2.Nombre.setBackground(Color.white);
    Lab2.comenzar.setEnabled(true);
    Lab2.Pause.setEnabled(false);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea2.setIcon(imagen);
    Lab2.Icono.setText("");
    Lab2.estado.setText("Normal");
    Lab2.estado.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[1])){ 
    Lab2.Nombre1.setEditable(true);
    Lab2.Nombre1.setEnabled(true);
    Lab2.Nombre1.setBackground(Color.white);
    Lab2.comenzar1.setEnabled(true);
    Lab2.Pause1.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea39.setIcon(imagen);
    Lab2.Icono1.setText("");
    Lab2.estado1.setText("Normal");
    Lab2.estado1.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[2])){ 
    Lab2.Nombre2.setEditable(true);
    Lab2.Nombre2.setEnabled(true);
    Lab2.Nombre2.setBackground(Color.white);
    Lab2.comenzar2.setEnabled(true);
    Lab2.Pause2.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea41.setIcon(imagen);
    Lab2.Icono2.setText("");
    Lab2.estado2.setText("Normal");
    Lab2.estado2.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[3])){ 
    Lab2.Nombre3.setEditable(true);
    Lab2.Nombre3.setEnabled(true);
    Lab2.Nombre3.setBackground(Color.white);
    Lab2.comenzar3.setEnabled(true);
    Lab2.Pause3.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea43.setIcon(imagen);
    Lab2.Icono3.setText("");
    Lab2.estado3.setText("Normal");
    Lab2.estado3.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[4])){ 
    Lab2.Nombre4.setEditable(true);
    Lab2.Nombre4.setEnabled(true);
    Lab2.Nombre4.setBackground(Color.white);
    Lab2.comenzar4.setEnabled(true);
    Lab2.Pause4.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea45.setIcon(imagen);
    Lab2.Icono4.setText("");
    Lab2.estado4.setText("Normal");
    Lab2.estado4.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[5])){ 
    Lab2.Nombre5.setEditable(true);
    Lab2.Nombre5.setEnabled(true);
    Lab2.Nombre5.setBackground(Color.white);
    Lab2.comenzar5.setEnabled(true);
    Lab2.Pause5.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea47.setIcon(imagen);
    Lab2.Icono5.setText("");
    Lab2.estado5.setText("Normal");
    Lab2.estado5.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[6])){ 
    Lab2.Nombre6.setEditable(true);
    Lab2.Nombre6.setEnabled(true);
    Lab2.Nombre6.setBackground(Color.white);
    Lab2.comenzar6.setEnabled(true);
    Lab2.Pause6.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea3.setIcon(imagen);
    Lab2.Icono6.setText("");
    Lab2.estado6.setText("Normal");
    Lab2.estado6.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[7])){ 
    Lab2.Nombre7.setEditable(true);
    Lab2.Nombre7.setEnabled(true);
    Lab2.Nombre7.setBackground(Color.white);
    Lab2.comenzar7.setEnabled(true);
    Lab2.Pause7.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea5.setIcon(imagen);
    Lab2.Icono7.setText("");
    Lab2.estado7.setText("Normal");
    Lab2.estado7.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[8])){ 
    Lab2.Nombre8.setEditable(true);
    Lab2.Nombre8.setEnabled(true);
    Lab2.Nombre8.setBackground(Color.white);
    Lab2.comenzar8.setEnabled(true);
    Lab2.Pause8.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea7.setIcon(imagen);
    Lab2.Icono8.setText("");
    Lab2.estado8.setText("Normal");
    Lab2.estado8.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[9])){ 
    Lab2.Nombre9.setEditable(true);
    Lab2.Nombre9.setEnabled(true);
    Lab2.Nombre9.setBackground(Color.white);
    Lab2.comenzar9.setEnabled(true);
    Lab2.Pause9.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea9.setIcon(imagen);
    Lab2.Icono9.setText("");
    Lab2.estado9.setText("Normal");
    Lab2.estado9.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[10])){ 
    Lab2.Nombre10.setEditable(true);
    Lab2.Nombre10.setEnabled(true);
    Lab2.Nombre10.setBackground(Color.white);
    Lab2.comenzar10.setEnabled(true);
    Lab2.Pause10.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea11.setIcon(imagen);
    Lab2.Icono10.setText("");
    Lab2.estado10.setText("Normal");
    Lab2.estado10.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[11])){ 
    Lab2.Nombre11.setEditable(true);
    Lab2.Nombre11.setEnabled(true);
    Lab2.Nombre11.setBackground(Color.white);
    Lab2.comenzar11.setEnabled(true);
    Lab2.Pause11.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea13.setIcon(imagen);
    Lab2.Icono11.setText("");
    Lab2.estado11.setText("Normal");
    Lab2.estado11.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[12])){ 
    Lab2.Nombre12.setEditable(true);
    Lab2.Nombre12.setEnabled(true);
    Lab2.Nombre12.setBackground(Color.white);
    Lab2.comenzar12.setEnabled(true);
    Lab2.Pause12.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea15.setIcon(imagen);
    Lab2.Icono12.setText("");
    Lab2.estado12.setText("Normal");
    Lab2.estado12.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[13])){ 
    Lab2.Nombre13.setEditable(true);
    Lab2.Nombre13.setEnabled(true);
    Lab2.Nombre13.setBackground(Color.white);
    Lab2.comenzar13.setEnabled(true);
    Lab2.Pause13.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea17.setIcon(imagen);
    Lab2.Icono13.setText("");
    Lab2.estado13.setText("Normal");
    Lab2.estado13.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[14])){ 
    Lab2.Nombre14.setEditable(true);
    Lab2.Nombre14.setEnabled(true);
    Lab2.Nombre14.setBackground(Color.white);
    Lab2.comenzar14.setEnabled(true);
    Lab2.Pause14.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea19.setIcon(imagen);
    Lab2.Icono14.setText("");
    Lab2.estado14.setText("Normal");
    Lab2.estado14.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[15])){ 
    Lab2.Nombre15.setEditable(true);
    Lab2.Nombre15.setEnabled(true);
    Lab2.Nombre15.setBackground(Color.white);
    Lab2.comenzar15.setEnabled(true);
    Lab2.Pause15.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea21.setIcon(imagen);
    Lab2.Icono15.setText("");
    Lab2.estado15.setText("Normal");
    Lab2.estado15.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[16])){ 
    Lab2.Nombre16.setEditable(true);
    Lab2.Nombre16.setEnabled(true);
    Lab2.Nombre16.setBackground(Color.white);
    Lab2.comenzar16.setEnabled(true);
    Lab2.Pause16.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea23.setIcon(imagen);
    Lab2.Icono16.setText("");
    Lab2.estado16.setText("Normal");
    Lab2.estado16.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[17])){ 
    Lab2.Nombre17.setEditable(true);
    Lab2.Nombre17.setEnabled(true);
    Lab2.Nombre17.setBackground(Color.white);
    Lab2.comenzar17.setEnabled(true);
    Lab2.Pause17.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea25.setIcon(imagen);
    Lab2.Icono17.setText("");
    Lab2.estado17.setText("Normal");
    Lab2.estado17.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[18])){ 
    Lab2.Nombre18.setEditable(true);
    Lab2.Nombre18.setEnabled(true);
    Lab2.Nombre18.setBackground(Color.white);
    Lab2.comenzar18.setEnabled(true);
    Lab2.Pause18.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea27.setIcon(imagen);
    Lab2.Icono18.setText("");
    Lab2.estado18.setText("Normal");
    Lab2.estado18.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[19])){ 
    Lab2.Nombre19.setEditable(true);
    Lab2.Nombre19.setEnabled(true);
    Lab2.Nombre19.setBackground(Color.white);
    Lab2.comenzar19.setEnabled(true);
    Lab2.Pause19.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea29.setIcon(imagen);
    Lab2.Icono19.setText("");
    Lab2.estado19.setText("Normal");
    Lab2.estado19.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[20])){ 
    Lab2.Nombre20.setEditable(true);
    Lab2.Nombre20.setEnabled(true);
    Lab2.Nombre20.setBackground(Color.white);
    Lab2.comenzar20.setEnabled(true);
    Lab2.Pause20.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea31.setIcon(imagen);
    Lab2.Icono20.setText("");
    Lab2.estado20.setText("Normal");
    Lab2.estado20.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[21])){ 
    Lab2.Nombre21.setEditable(true);
    Lab2.Nombre21.setEnabled(true);
    Lab2.Nombre21.setBackground(Color.white);
    Lab2.comenzar21.setEnabled(true);
    Lab2.Pause21.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea33.setIcon(imagen);
    Lab2.Icono21.setText("");
    Lab2.estado21.setText("Normal");
    Lab2.estado21.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[22])){ 
    Lab2.Nombre22.setEditable(true);
    Lab2.Nombre22.setEnabled(true);
    Lab2.Nombre22.setBackground(Color.white);
    Lab2.comenzar22.setEnabled(true);
    Lab2.Pause22.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea35.setIcon(imagen);
    Lab2.Icono22.setText("");
    Lab2.estado22.setText("Normal");
    Lab2.estado22.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    if(r.getText().equals(m[23])){ 
    Lab2.Nombre23.setEditable(true);
    Lab2.Nombre23.setEnabled(true);
    Lab2.Nombre23.setBackground(Color.white);
    Lab2.comenzar23.setEnabled(true);
    Lab2.Pause23.setEnabled(true);
    ImageIcon imagen = new ImageIcon (getClass().getResource("/pictures/monitor-2455524__340.png"));
    Lab2.Idea37.setIcon(imagen);
    Lab2.Icono23.setText("");
    Lab2.estado23.setText("Normal");
    Lab2.estado23.setBackground(Color.green);
    dispose();
    this.setVisible(false);
    }
    
    }
    }//GEN-LAST:event_AceptoActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
    
    }//GEN-LAST:event_NActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(State2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(State2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(State2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(State2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new State2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acepto;
    private javax.swing.ButtonGroup Estados;
    public static javax.swing.JRadioButton FS;
    public static javax.swing.JRadioButton N;
    public static javax.swing.JRadioButton NoI;
    private javax.swing.JLabel R;
    private javax.swing.JButton Vp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField r;
    // End of variables declaration//GEN-END:variables
}
