/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author PC1
 */
public class Eventos2 extends javax.swing.JFrame {

    /**
     * Creates new form Eventos2
     */
    public Eventos2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/bloquear.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DIA = new javax.swing.JSpinner();
        MES = new javax.swing.JSpinner();
        AÑO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Eventos = new javax.swing.JComboBox<>();
        f1 = new javax.swing.JLabel();
        GUARDAR1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NOMBRES = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LUGAR = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        No = new javax.swing.JSpinner();
        GUARDAR2 = new javax.swing.JButton();
        FECHA = new javax.swing.JTextField();
        ENVIAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MENSAJE = new javax.swing.JTextArea();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Gestión de eventos en Áreas comunes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 30));

        DIA.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jPanel2.add(DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 30));

        MES.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanel2.add(MES, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, 30));

        AÑO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AÑO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027" }));
        AÑO.setSelectedIndex(-1);
        jPanel2.add(AÑO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 70, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Evento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 30));

        Eventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reunión", "Boda", "Cumpleaños", "Fiesta Religiosa", "Fiesta" }));
        Eventos.setSelectedIndex(-1);
        Eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosActionPerformed(evt);
            }
        });
        jPanel2.add(Eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, 30));

        f1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        f1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1.setText("DESCRIPCIÓN");
        f1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        f1.setOpaque(true);
        jPanel2.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 190, 150));

        GUARDAR1.setBackground(new java.awt.Color(255, 102, 0));
        GUARDAR1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GUARDAR1.setText("ENVIAR");
        GUARDAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDAR1ActionPerformed(evt);
            }
        });
        jPanel2.add(GUARDAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Organizadores");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, -1));
        jPanel2.add(NOMBRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 30));

        jLabel5.setText("Lugar del Evento");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        LUGAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Parque", "Estacionamiento", "Edificio (Privado)", " " }));
        LUGAR.setSelectedIndex(-1);
        LUGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUGARActionPerformed(evt);
            }
        });
        jPanel2.add(LUGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("No. de Casa");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        No.setModel(new javax.swing.SpinnerNumberModel(1, 1, 41, 1));
        No.setEnabled(false);
        No.setValue(1);
        jPanel2.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 40, -1));

        GUARDAR2.setBackground(new java.awt.Color(255, 204, 51));
        GUARDAR2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GUARDAR2.setText("GUARDAR");
        GUARDAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDAR2ActionPerformed(evt);
            }
        });
        jPanel2.add(GUARDAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 30));

        FECHA.setColumns(2);
        jPanel2.add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 40));

        ENVIAR.setBackground(new java.awt.Color(102, 153, 255));
        ENVIAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ENVIAR.setText("ENVIAR");
        jPanel2.add(ENVIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Descripción");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 90, 20));

        MENSAJE.setEditable(false);
        MENSAJE.setColumns(20);
        MENSAJE.setLineWrap(true);
        MENSAJE.setRows(5);
        MENSAJE.setWrapStyleWord(true);
        MENSAJE.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(MENSAJE);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 300, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 390));

        Salir.setBackground(new java.awt.Color(255, 0, 0, 80));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/p.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosActionPerformed
       
       int o1= Eventos.getSelectedIndex();
       f1.setText("");
       if(o1==0){
       f1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Eventos/E1.jpg")));    
       }
       if(o1==1){
       f1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Eventos/E2.jpeg")));   
       }
       if(o1==2){
       f1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Eventos/E3.jpg")));   
       }
       if(o1==3){
       f1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Eventos/E4.jpg")));   
       }
        if(o1==4){
       f1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Eventos/E5.jpg")));   
       }
    }//GEN-LAST:event_EventosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void GUARDAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDAR1ActionPerformed
           String f="";
           int a=Integer.parseInt((String) AÑO.getSelectedItem()); 
           int m= (int) MES.getValue();
           int d= (int) DIA.getValue();
           f=" Dia: "+d+" Mes: "+m+" Año: "+a;
           FECHA.setText(f);
    }//GEN-LAST:event_GUARDAR1ActionPerformed

    private void LUGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUGARActionPerformed
       String l= (String) LUGAR.getSelectedItem();
       if(l.equals("Casa")){
           No.setEnabled(true);
       }else{
           No.setEnabled(false);
       }
    }//GEN-LAST:event_LUGARActionPerformed

    private void GUARDAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDAR2ActionPerformed
        String c="";
         int i=0;
        String añ[] = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre",
    "Octubre","Noviembre","Diciembre"};
        String a=(String) AÑO.getSelectedItem();
        int m= (int) MES.getValue();
     if(LUGAR.getSelectedItem().toString().equals("Casa")){
     c=NOMBRES.getText()+" organizarán un(a) "+ (String)Eventos.getSelectedItem()+
        " ,en su "+(String)LUGAR.getSelectedItem()+ " No."+No.getValue()+".\n"+
            "El Dia: "+DIA.getValue()+" de "+añ[m-1]+" del año: "+a+" .\n";
     }else{
     c=NOMBRES.getText()+" organizarán un(a) "+ (String)Eventos.getSelectedItem()+
        " ,en el "+(String)LUGAR.getSelectedItem()+".\n"+
            "El Dia: "+DIA.getValue()+" de "+añ[m-1]+" del año: "+a+" .\n";
     }

     MENSAJE.setText(c);
    }//GEN-LAST:event_GUARDAR2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventos2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AÑO;
    private javax.swing.JSpinner DIA;
    private javax.swing.JButton ENVIAR;
    private javax.swing.JComboBox<String> Eventos;
    private javax.swing.JTextField FECHA;
    private javax.swing.JButton GUARDAR1;
    private javax.swing.JButton GUARDAR2;
    private javax.swing.JComboBox<String> LUGAR;
    private javax.swing.JTextArea MENSAJE;
    private javax.swing.JSpinner MES;
    private javax.swing.JTextField NOMBRES;
    private javax.swing.JSpinner No;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
