/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase2;
import javax.swing.*;
/**
 *
 * @author Alejandra
 */
public class frmCurso extends javax.swing.JFrame {
// para los Jlist que se lleban en base a la seleccion del boton
    private DefaultListModel modelo1=new DefaultListModel();
    private DefaultListModel modelo2=new DefaultListModel();
    
    public frmCurso() {
        initComponents();
        //habilitar los JListe que se llenan automaticamente
        lstCursos1.setModel(modelo1);
        lstCostos1.setModel(modelo2);
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCurso = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCosto = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCursos1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCostos1 = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstCurso.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "C++", "C#", "Java", "Delphi", "Phyton" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCurso.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCurso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 200));

        lstCosto.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1200", "1345", "2679", "4563", "7865", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCosto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCostoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstCosto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, 200));

        lstCursos1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursos1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCursos1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 70, 200));

        lstCostos1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCostos1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstCostos1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 50, 200));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtTotal.setText("               ");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel1.setText("Alumno:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jTextField1.setText("                                   ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String curso,costo;
        int cuenta,i,total=0;
        curso=(String)lstCurso.getSelectedValue();
        costo=(String)lstCosto.getSelectedValue();
        modelo1.addElement(curso);
        modelo2.addElement(costo);
        cuenta=modelo2.size();
        for(i=0;i<cuenta;i++){
            total=total+Integer.parseInt((String)modelo2.elementAt(i));
          }
        txtTotal.setText(String.valueOf(total));
        btnAgregar.setEnabled(false);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void lstCursoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursoValueChanged
        // TODO add your handling code here:
        int indice;
        indice=lstCurso.getSelectedIndex();
        lstCosto.setSelectedIndex(indice);
        btnAgregar.setEnabled(true);
    }//GEN-LAST:event_lstCursoValueChanged

    private void lstCostoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCostoValueChanged
        // TODO add your handling code here
        
    }//GEN-LAST:event_lstCostoValueChanged

    private void lstCursos1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursos1ValueChanged
        // TODO add your handling code here:
        int indice;
        indice=lstCursos1.getSelectedIndex();
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_lstCursos1ValueChanged

    private void lstCostos1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCostos1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstCostos1ValueChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int indice,cuenta,i,total=0;
        indice=lstCursos1.getSelectedIndex();
        modelo1.remove(indice);
        modelo2.remove(indice);
        cuenta=modelo2.size();
        for(i=0;i<cuenta;i++){
            total=total+Integer.parseInt((String)modelo2.elementAt(i));
          }
        txtTotal.setText(String.valueOf(total));
        btnEliminar.setEnabled(false);
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> lstCosto;
    private javax.swing.JList<String> lstCostos1;
    private javax.swing.JList<String> lstCurso;
    private javax.swing.JList<String> lstCursos1;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
