/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC1
 */
public class ServiciosB extends javax.swing.JFrame {
    
    DefaultTableModel mo1= new DefaultTableModel();
    int s;
    public ServiciosB() {
        initComponents();
        String t[]= {"Agua","Luz"};
        String t1[]={"Tarifa 1","0.882 $/kWh"};
        String t2[]={"Tarifa 1A","0.786 $/kWh"};
        String t3[]={"Tarifa 1B","0.987 $/kWh"};
        mo1.setColumnIdentifiers(t);
        mo1.addRow(t1);
        mo1.addRow(t2);
        mo1.addRow(t3);
        this.T1.setModel(mo1);
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/L4.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        potencia = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        hpd = new javax.swing.JSpinner();
        GENERAR1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        Consumo = new javax.swing.JTextField();
        CALCULAR = new javax.swing.JButton();
        tarifa = new javax.swing.JComboBox<>();
        dum = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        L = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CONSUMO2 = new javax.swing.JTextField();
        CALCULAR2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        M3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        NAME2 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(650, 370));
        setUndecorated(true);
        setSize(new java.awt.Dimension(650, 390));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro del consumo de lecturas del agua y la luz");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        Salir.setBackground(new java.awt.Color(255, 0, 0,100));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/p.png"))); // NOI18N
        Salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 70));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Días de uso al mes");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Apellidos");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));
        jPanel8.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, -1));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Potencia(W)");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel8.add(potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, -1));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Horas de uso por día");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        hpd.setModel(new javax.swing.SpinnerNumberModel(1, 1, 14, 1));
        hpd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hpdStateChanged(evt);
            }
        });
        jPanel8.add(hpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, -1));

        GENERAR1.setBackground(new java.awt.Color(204, 0, 0));
        GENERAR1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GENERAR1.setForeground(new java.awt.Color(255, 255, 255));
        GENERAR1.setText("RECIBO");
        jPanel8.add(GENERAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 100, 40));

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Nombre");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel8.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, -1));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Kwh/Mes");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        T1.setAutoCreateRowSorter(true);
        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarifa", "Consumo Básico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        T1.setFocusable(false);
        jScrollPane3.setViewportView(T1);
        T1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 250, 80));

        Consumo.setEditable(false);
        Consumo.setBackground(new java.awt.Color(255, 255, 255));
        Consumo.setForeground(new java.awt.Color(0, 0, 0));
        Consumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Consumo.setText("CONSUMO MENSUAL");
        jPanel8.add(Consumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 30));

        CALCULAR.setBackground(new java.awt.Color(153, 0, 51));
        CALCULAR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALCULAR.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR.setText("Calcular");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        jPanel8.add(CALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 40));

        tarifa.setBackground(new java.awt.Color(255, 255, 255));
        tarifa.setForeground(new java.awt.Color(0, 0, 0));
        tarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarifa 1", "Tarifa 1A", "Tarifa 1B" }));
        jPanel8.add(tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 140, -1));

        dum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        jPanel8.add(dum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 60, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 230));

        jTabbedPane1.addTab("Lectura de la luz", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 50, -1));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("m3");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Litros");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        CONSUMO2.setEditable(false);
        CONSUMO2.setBackground(new java.awt.Color(255, 255, 255));
        CONSUMO2.setForeground(new java.awt.Color(0, 0, 0));
        CONSUMO2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CONSUMO2.setText("CONSUMO MENSUAL");
        jPanel5.add(CONSUMO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, 30));

        CALCULAR2.setBackground(new java.awt.Color(153, 0, 51));
        CALCULAR2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALCULAR2.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR2.setText("Calcular");
        CALCULAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR2ActionPerformed(evt);
            }
        });
        jPanel5.add(CALCULAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Nombre");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel5.add(M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("x metró cubico");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        NAME2.setEditable(false);
        NAME2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(NAME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, -1));

        A2.setEditable(false);
        A2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, -1));

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Apellidos");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 420, 210));

        jTabbedPane1.addTab("Lectura del agua", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 510, 280));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F7.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        MenuP m= new MenuP();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        int c;
        c =  Integer.parseInt(potencia.getText())*(int) hpd.getValue()*(int) dum.getValue();
        Consumo.setText(Integer.toString(c));
    }//GEN-LAST:event_CALCULARActionPerformed

    private void hpdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hpdStateChanged
        
    }//GEN-LAST:event_hpdStateChanged

    private void CALCULAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR2ActionPerformed
        
    }//GEN-LAST:event_CALCULAR2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiciosB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A2;
    private javax.swing.ButtonGroup BG;
    private javax.swing.JButton CALCULAR;
    private javax.swing.JButton CALCULAR2;
    private javax.swing.JTextField CONSUMO2;
    private javax.swing.JTextField Consumo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton GENERAR1;
    private javax.swing.JTextField L;
    private javax.swing.JTextField M3;
    private javax.swing.JTextField NAME2;
    private javax.swing.JButton Salir;
    private javax.swing.JTable T1;
    private javax.swing.JSpinner dum;
    private javax.swing.JSpinner hpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField potencia;
    private javax.swing.JComboBox<String> tarifa;
    // End of variables declaration//GEN-END:variables
}
